# Backend/alembic.ini
# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# timezone = UTC

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions, even if
# the source is not present. This is useful for .pyo/.pyc files
# that have been compiled to improve load time, but it may
# indicate an unreferenced revision.
# ignore_revision_files = false

# The encoding of the revision files.
# revision_encoding = utf-8

# sqlalchemy.url = driver://user:pass@localhost/dbname
sqlalchemy.url = postgresql+asyncpg://commerce_user:commerce_pass@localhost:5432/commerce_db


[post_write_hooks]
# post_write_hooks defines hooks which are run after a new
# revision file has been created. These hooks are used to add
# additional formatting or content to the generated file.
# 
# Post write hook scripts must be callable, and take two
# arguments: the path to the revision file, and the options
# dict passed to the revision command.
#
# The `hooks` setting lists the hook names to run. They will be
# looked up in the `post_write_hooks` section of the config
# by name.
# hooks = black, mypy

# black = black -l 88 {filename}
# mypy = mypy --ignore-missing-imports {filename}

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S